#!/bin/bash

domain="$1"
subdomain="$2"

# Define function to query DNS records
query_dns() {
    dig "$1"."$domain" | awk '/ANSWER SECTION/ {getline; print $NF}'
}

# If subdomain is not provided, query default subdomains
if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

# Iterate over subdomains and display information
for sub in "${subdomains[@]}"; do
    record_type=$(query_dns "$sub" | awk '{print $2}')
    destination=$(query_dns "$sub")
    echo "The subdomain $sub is a $record_type record and points to $destination"
done
