#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection for a specific endpoint
string_for_redirect="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=fxiW3oQCan4 permanent;"
sudo sed -i "s/server_name _;/$string_for_redirect/" /etc/nginx/sites-enabled/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
string_for_error="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_error/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
